version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - arsipnet

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arsipdb
    ports:
      - "5432:5432"
    networks:
      - arsipnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - arsipnet

networks:
  arsipnet:
    driver: bridge
